# Generated by Django 4.2 on 2023-04-30 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xtest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': '留言信息', 'verbose_name_plural': '留言信息'},
        ),
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
    ]
